# Stage 1: Build the application
FROM node:13.12.0-alpine as build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Construir la aplicación
RUN npm run build

# Stage 2: Production image
FROM node:13.12.0-alpine

# Establecer el directorio de trabajo en el nuevo contenedor
WORKDIR /app

# Copiar los archivos de la etapa de construcción
COPY --from=build /app .

# Exponer el puerto 3000 en el contenedor
EXPOSE 3000

# Comando para ejecutar la aplicación en producción
CMD ["npm", "start"]
